# Generated by Django 5.1.6 on 2025-03-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="embed_code",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
